"""Add hidden prpoerty to family and article

Revision ID: 01f89c3f0388
Revises: 4c290672ec51
Create Date: 2024-10-18 13:36:59.157865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01f89c3f0388'
down_revision = '4c290672ec51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden', mysql.TINYINT(display_width=1), nullable=True))

    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden', mysql.TINYINT(display_width=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.drop_column('hidden')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('hidden')

    # ### end Alembic commands ###
