"""Add new models

Revision ID: 0606a2dd8ca7
Revises: 401953e15d9a
Create Date: 2025-04-22 14:13:32.552508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0606a2dd8ca7'
down_revision = '401953e15d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_sales',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('first_ticket', sa.Integer(), nullable=False),
    sa.Column('last_ticket', sa.Integer(), nullable=False),
    sa.Column('total_sold', sa.Float(), nullable=False),
    sa.Column('previous_balance', sa.Float(), nullable=False),
    sa.Column('current_balance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'counter')
    )
    op.create_table('tickets',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('closed_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['closed_at'], ['daily_sales.date'], ),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('ticket_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_number', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=50), nullable=True),
    sa.Column('codebar', sa.String(length=50), nullable=True),
    sa.Column('detalle', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_number'], ['tickets.number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_items')
    op.drop_table('tickets')
    op.drop_table('daily_sales')
    # ### end Alembic commands ###
