"""Update family model

Revision ID: 2d2241aad10e
Revises: 4d77e6e42d08
Create Date: 2025-12-04 15:07:27.453348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d2241aad10e'
down_revision = '4d77e6e42d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('icon_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('icon_color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.drop_column('icon_color')
        batch_op.drop_column('icon_name')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
