"""Init

Revision ID: 381678e1ab8c
Revises: 
Create Date: 2025-02-17 17:00:52.620755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '381678e1ab8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family',
    sa.Column('codfam', sa.Integer(), nullable=False),
    sa.Column('nomfam', sa.String(length=50), nullable=False),
    sa.Column('hidden', mysql.TINYINT(display_width=1), nullable=True),
    sa.PrimaryKeyConstraint('codfam')
    )
    op.create_table('otp_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('article',
    sa.Column('ref', mysql.BIGINT(), nullable=False),
    sa.Column('detalle', sa.String(length=50), nullable=True),
    sa.Column('codfam', sa.Integer(), nullable=True),
    sa.Column('pcosto', sa.Float(), nullable=True),
    sa.Column('pvp', sa.Float(), nullable=False),
    sa.Column('codebar', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('factualizacion', sa.DateTime(), nullable=True),
    sa.Column('destacado', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('hidden', mysql.TINYINT(display_width=1), nullable=True),
    sa.ForeignKeyConstraint(['codfam'], ['family.codfam'], ),
    sa.PrimaryKeyConstraint('codebar')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_codfam'), ['codfam'], unique=False)

    op.create_table('article_imports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('new_rows', sa.Integer(), nullable=True),
    sa.Column('updated_rows', sa.Integer(), nullable=True),
    sa.Column('deleted_rows', sa.Integer(), nullable=True),
    sa.Column('duplicated_rows', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_imports_user_id'), ['user_id'], unique=False)

    op.create_table('article_import_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=50), nullable=True),
    sa.Column('codebar', sa.String(length=50), nullable=True),
    sa.Column('detalle', sa.String(length=100), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['article_imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_import_logs')
    with op.batch_alter_table('article_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_imports_user_id'))

    op.drop_table('article_imports')
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_codfam'))

    op.drop_table('article')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('otp_codes')
    op.drop_table('family')
    # ### end Alembic commands ###
