"""Modify ticket foreign key

Revision ID: 401953e15d9a
Revises: 0b34bd4d0f4a
Create Date: 2025-04-22 13:02:48.245051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401953e15d9a'
down_revision = '0b34bd4d0f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint('tickets_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'daily_sales', ['closed_at'], ['date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tickets_ibfk_1', 'daily_sales', ['date'], ['date'])

    # ### end Alembic commands ###
