"""Fixes

Revision ID: 4fdcb334658b
Revises: 0606a2dd8ca7
Create Date: 2025-05-01 03:08:15.801641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fdcb334658b'
down_revision = '0606a2dd8ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_items', schema=None) as batch_op:
        batch_op.alter_column('detalle',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_items', schema=None) as batch_op:
        batch_op.alter_column('detalle',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
