"""Fix relationships

Revision ID: 58bb900713ec
Revises: 381678e1ab8c
Create Date: 2025-02-17 20:40:10.210034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58bb900713ec'
down_revision = '381678e1ab8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index('detalle_index', ['detalle'], unique=False, mysql_prefix='FULLTEXT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index('detalle_index', mysql_prefix='FULLTEXT')

    # ### end Alembic commands ###
