"""Add new models

Revision ID: 6cdf3e51ac89
Revises: fca1191e373b
Create Date: 2025-04-22 18:06:38.373500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6cdf3e51ac89'
down_revision = 'fca1191e373b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_sales',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('first_ticket', sa.Integer(), nullable=False),
    sa.Column('last_ticket', sa.Integer(), nullable=False),
    sa.Column('total_sold', sa.Float(), nullable=False),
    sa.Column('previous_balance', sa.Float(), nullable=False),
    sa.Column('current_balance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'counter')
    )
    op.create_table('tickets',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('closed_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['closed_at'], ['daily_sales.date'], ),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('ticket_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_number', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=50), nullable=True),
    sa.Column('codebar', sa.String(length=50), nullable=True),
    sa.Column('detalle', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_number'], ['tickets.number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('detalle',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('detalle',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'),
               existing_nullable=True)

    op.drop_table('ticket_items')
    op.drop_table('tickets')
    op.drop_table('daily_sales')
    # ### end Alembic commands ###
