"""Add date_created to articles

Revision ID: 73513ac95bc7
Revises: 58bb900713ec
Create Date: 2025-02-25 09:21:02.968890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73513ac95bc7'
down_revision = '58bb900713ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    with op.batch_alter_table('article_imports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('corrected', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('elapsed_time', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_imports', schema=None) as batch_op:
        batch_op.drop_column('elapsed_time')
        batch_op.drop_column('corrected')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
