"""Add article_images table

Revision ID: 75aefda65438
Revises: d88adc7f5b7c
Create Date: 2025-07-11 18:06:28.334578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75aefda65438'
down_revision = 'd88adc7f5b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_images',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('article_codebar', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('is_main', mysql.TINYINT(display_width=1), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('article_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_images_article_codebar'), ['article_codebar'], unique=False)

    with op.batch_alter_table('ticket_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_items_codebar'), ['codebar'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_items_ref'), ['ref'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_items_ref'))
        batch_op.drop_index(batch_op.f('ix_ticket_items_codebar'))

    with op.batch_alter_table('article_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_images_article_codebar'))

    op.drop_table('article_images')
    # ### end Alembic commands ###
