"""Fix column

Revision ID: 7f4b8f98d576
Revises: 6cdf3e51ac89
Create Date: 2025-04-22 20:36:10.604822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f4b8f98d576'
down_revision = '6cdf3e51ac89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_items', schema=None) as batch_op:
        batch_op.alter_column('detalle',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_items', schema=None) as batch_op:
        batch_op.alter_column('detalle',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
