"""Add new tables. Logs.

Revision ID: aac1abd4f9a3
Revises: cf7361bed2af
Create Date: 2025-02-17 23:23:46.596940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aac1abd4f9a3'
down_revision = 'cf7361bed2af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_imports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('new_rows', sa.Integer(), nullable=True),
    sa.Column('updated_rows', sa.Integer(), nullable=True),
    sa.Column('deleted_rows', sa.Integer(), nullable=True),
    sa.Column('duplicated_rows', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('elapsed_time', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_imports_user_id'), ['user_id'], unique=False)

    op.create_table('article_import_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=50), nullable=True),
    sa.Column('codebar', sa.String(length=50), nullable=True),
    sa.Column('detalle', sa.String(length=100), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['import_id'], ['article_imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('hidden',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.create_index('detalle_index', ['detalle'], unique=False, mysql_prefix='FULLTEXT')

    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.alter_column('hidden',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family', schema=None) as batch_op:
        batch_op.alter_column('hidden',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index('detalle_index', mysql_prefix='FULLTEXT')
        batch_op.alter_column('hidden',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    op.drop_table('article_import_logs')
    with op.batch_alter_table('article_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_imports_user_id'))

    op.drop_table('article_imports')
    # ### end Alembic commands ###
