"""Add new tables for sales statistics

Revision ID: b99d219556a9
Revises: 73513ac95bc7
Create Date: 2025-04-17 19:10:46.224597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b99d219556a9'
down_revision = '73513ac95bc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_sales',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('first_ticket', sa.Integer(), nullable=False),
    sa.Column('last_ticket', sa.Integer(), nullable=False),
    sa.Column('total_sold', sa.Float(), nullable=False),
    sa.Column('previous_balance', sa.Float(), nullable=False),
    sa.Column('current_balance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('tickets',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('closed_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['date'], ['daily_sales.date'], ),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('ticket_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_number', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=50), nullable=True),
    sa.Column('codebar', sa.String(length=50), nullable=True),
    sa.Column('detalle', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_number'], ['tickets.number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('detalle',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('detalle',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    op.drop_table('ticket_items')
    op.drop_table('tickets')
    op.drop_table('daily_sales')
    # ### end Alembic commands ###
