"""Fix ImportFile table column

Revision ID: c1905e6fe650
Revises: e87e05e0c298
Create Date: 2025-09-17 21:06:44.093854

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1905e6fe650'
down_revision = 'e87e05e0c298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_message', sa.Text(), nullable=True))
        batch_op.drop_column('error_message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_message', mysql.TEXT(), nullable=True))
        batch_op.drop_column('status_message')

    # ### end Alembic commands ###
