"""Change codebar and ref type

Revision ID: d88adc7f5b7c
Revises: 7f4b8f98d576
Create Date: 2025-07-09 14:33:54.666940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd88adc7f5b7c'
down_revision = '7f4b8f98d576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('ref',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('codebar',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               autoincrement=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.alter_column('codebar',
               existing_type=sa.String(length=50),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False,
               autoincrement=False)
        batch_op.alter_column('ref',
               existing_type=sa.String(length=50),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)

    # ### end Alembic commands ###
