"""Inital migration

Revision ID: da43ff8b9791
Revises: 
Create Date: 2024-09-11 14:10:40.680516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da43ff8b9791'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family',
    sa.Column('codfam', sa.Integer(), nullable=False),
    sa.Column('nomfam', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('codfam')
    )
    op.create_table('article',
    sa.Column('ref', mysql.BIGINT(), nullable=False),
    sa.Column('detalle', sa.String(length=50), nullable=True),
    sa.Column('codfam', sa.Integer(), nullable=True),
    sa.Column('pcosto', sa.Float(), nullable=True),
    sa.Column('pvp', sa.Float(), nullable=False),
    sa.Column('codebar', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('factualizacion', sa.DateTime(), nullable=True),
    sa.Column('destacado', mysql.TINYINT(display_width=1), nullable=True),
    sa.ForeignKeyConstraint(['codfam'], ['family.codfam'], ),
    sa.PrimaryKeyConstraint('codebar')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_article_codfam'), ['codfam'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_article_codfam'))

    op.drop_table('article')
    op.drop_table('family')
    # ### end Alembic commands ###
