"""Fix ImportFile table name

Revision ID: e87e05e0c298
Revises: 16ae4bef2d36
Create Date: 2025-09-17 16:26:27.765276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e87e05e0c298'
down_revision = '16ae4bef2d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filetype', sa.Enum('articles', 'families', 'stocks', 'cierre', 'movimt', 'hticketl'), nullable=False),
    sa.Column('filepath', sa.String(length=512), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'error'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('files')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('filetype', mysql.ENUM('articles', 'families', 'stocks', 'cierre', 'movimt', 'hticketl'), nullable=False),
    sa.Column('filepath', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('uploaded_at', mysql.DATETIME(), nullable=False),
    sa.Column('status', mysql.ENUM('pending', 'processing', 'done', 'error'), nullable=False),
    sa.Column('attempts', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('last_attempt', mysql.DATETIME(), nullable=True),
    sa.Column('error_message', mysql.TEXT(), nullable=True),
    sa.Column('processed_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('import_files')
    # ### end Alembic commands ###
