"""Add new column to ImportFile model

Revision ID: f11168724726
Revises: c1905e6fe650
Create Date: 2025-09-18 00:09:41.568923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f11168724726'
down_revision = 'c1905e6fe650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_files', schema=None) as batch_op:
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
