"""Modify daily_sales model

Revision ID: fc2b121137b9
Revises: b99d219556a9
Create Date: 2025-04-19 20:28:56.650904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc2b121137b9'
down_revision = 'b99d219556a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('counter', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_sales', schema=None) as batch_op:
        batch_op.drop_column('counter')

    # ### end Alembic commands ###
