"""Application configuration."""
from environs import Env

env = Env()
env.read_env()


SECRET_KEY = env.str("SECRET_KEY")

INTERNAL_API_KEY = env.str("INTERNAL_API_KEY")

URL_SCHEME = env.str("URL_SCHEME")


SQLALCHEMY_DATABASE_URI = env.str("SQLALCHEMY_DATABASE_URI")
SQLALCHEMY_TRACK_MODIFICATIONS = False

SQLALCHEMY_ENGINE_OPTIONS = {
    "pool_pre_ping": True,
    "pool_recycle": 3600,
}


REDIS_DATABASE_HOST = env.str("REDIS_DATABASE_HOST")
REDIS_DATABASE_PORT = env.int("REDIS_DATABASE_PORT")

REDIS_IMPORTS_QUEUE = env.str("REDIS_IMPORTS_QUEUE")


CLOUDFLARE_API_TOKEN = env.str("CLOUDFLARE_API_TOKEN")
DNS_ZONE_ID = env.str("DNS_ZONE_ID")

TURNSTILE_VERIFY_URL = env.str("TURNSTILE_VERIFY_URL")
TURNSTILE_SECRET_KEY = env.str("TURNSTILE_SECRET_KEY")


PUSHOVER_APP_TOKEN = env.str("PUSHOVER_APP_TOKEN")
PUSHOVER_USER_KEY = env.str("PUSHOVER_USER_KEY")


DATA_ROUTE = env.str("DATA_ROUTE")

UPLOAD_ROUTE = env.str("UPLOAD_ROUTE")
MAX_CONTENT_LENGTH = env.int("MAX_CONTENT_LENGTH")

DATA_LOGS_ROUTE = env.str("DATA_LOGS_ROUTE")

IMAGES_ROUTE = env.str("IMAGES_ROUTE")

SCRIPTS_ROUTE = env.str("SCRIPTS_ROUTE")